###
GET http://localhost:8080/v1/images

###
POST http://localhost:8080/v1/images
Content-Type: application/json

{
  "isActive": true,
  "link": "https://upload.wikimedia.org/wikipedia/ru/7/7f/Habrahabr_logo.png",
  "image": "base64_format"
}

###
POST http://localhost:8080/v1/images/test
Content-Type: application/json

{
  "url": "https://xxx.html",
  "imageId": "662567dd4d8f1b6355a3dea7"
}