###
GET http://localhost:8080/v1/images

###
POST http://localhost:8080/v1/images
Content-Type: application/json

{
  "isActive": true,
  "defaultImage": "https://cdnstatic.rg.ru/images/rg-social-dummy-logo-650x360.jpg",
  "attributeClassName": "PageArticleContent",
  "additionalClassAttributes": [
    "Image",
    "img"
  ]
}

###
POST http://localhost:8080/v1/images/test
Content-Type: application/json

{
  "url": "https://xxx.html",
  "imageId": "662567dd4d8f1b6355a3dea7"
}