### Simple message format
POST http://localhost:${APP_SERVICE_PORT:8080}/v1/messages
Content-Type: application/json

{
  "chatId": -1001600823930,
  "text": "Hello java!"
}

### Message with image and text
POST http://localhost:${APP_SERVICE_PORT:8080}/v1/messages
Content-Type: application/json

{
  "chatId": -1001600823930,
  "image": "https://upload.wikimedia.org/wikipedia/ru/7/7f/Habrahabr_logo.png",
  "text": "Hello java!"
}