###
GET http://localhost:8080/v1/subscriptions

###
POST http://localhost:8080/v1/subscriptions
Content-Type: application/json

{
  "chatId": -1001600823930,
  "templateId": "6619963275ced443a63c3456",
  "rss": "https://site/xml/index.xml",
  "image": "https://logo-650x360.jpg",
  "filterIds": [
    "66218df402ace91dcffcddae",
    "662415cffc13084689b00a35"
  ],
  "isActive": true
}

###
PATCH http://localhost:8080/v1/subscriptions/66218f8b1512f67839bc5234